# Generated by Django 5.1 on 2024-08-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrvX8szwybkA8_2wFG8BrFkHVcQJFaVA6H_g&s', max_length=1000),
        ),
    ]
